name: Pipeline
on:
  workflow_call:
    inputs:
      branch:
        description: 'branch to checkout'
        required: false
        default: ''
        type: string
      chartFolder:
        required: false
        type: string
        default: 'chart'
      additionalTestFilesCommand:
        required: false
        type: string
        default: '-f chart/test-values.yaml'
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:
  # Validates the helm chart (lint/unittest)
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/project-jukebox/gha/infra/helm-unittest:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Linting Chart
        run: helm lint ${{ inputs.additionalTestFilesCommand }} ${{ inputs.chartFolder }}
      - name: Unit Testing Chart
        run: helm unittest ${{ inputs.chartFolder }}
  
