name: Docker

on:
  push:
    branches: [ nexus49-patch-1 ]
    paths:
      - '.github/workflows/infra-helm-unittest.yml'
      - 'infra/infra-helm-unittest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: infra/helm-unittest
        push: true
        tags: ghcr.io/${{ github.repository }}/infra/helm-unittest:latest