name: Node Test
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
      workingDirectory:
        required: false
        type: string
        default: './'
      mainBranchRef:
        required: false
        type: string
        default: 'refs/heads/main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Git
      run: |
        git config --global user.name 'OpenMFP Technical User'
        git config --global user.email 'openmfp@gmail.com'
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: "838464"
        private-key: ${{ secrets.OPENMFP_PUBLISHER_PRIVATE_KEY }}
    - uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
        ref: ${{ inputs.mainBranchRef }}
    - uses: actions/setup-node@v1
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/
    - name: Publish
      run: |
        npm version ${{inputs.version}} -m "[no ci] Release ${{inputs.version}}"
        npm publish
      working-directory: ${{ inputs.workingDirectory }}
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Commit, Tag and Push
      run: |
        git push origin
        git push origin --tags