name: Docker Build and Push
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ inputs.imageTagName }}:${{ inputs.version }}
          secrets: |
            NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
