name: COM
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      imageName:
        required: true
        type: string
      provider:
        required: true
        type: string
      componentName:
        required: true
        type: string
      componentDescriptorFile:
        required: true
        type: string
      componentRepo:
        required: true
        type: string
      chartFolder:
        required: true
        type: string
jobs:
  ocm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: setup OCM
        uses: open-component-model/ocm-setup-action@main
      - name: create OCM ComponentArchive
        uses: open-component-model/ocm-action@main
        with:
          action: add_component
          components: ${{ inputs.componentDescriptorFile }}
          directory: .ocm
          version: ${{ inputs.version }}
          templater: spiff
          var_values: |
            COMMIT: ${{ github.sha }}
            COMP_NAME: ${{ inputs.componentName }}
            IMAGE: ${{ inputs.imageName }}:${{ inputs.VERSION}}
            PROVIDER: ${{ inputs.provider }}
            REPO_URL: ${{ github.server_url }}/${{ github.repository }}
            VERSION: ${{ inputs.VERSION}}
            CHART_FOLDER: ${{ inputs.chartFolder }}
            HELM_REPO: ${{ github.repository }}/helm
      - name: transfer to OCI Repo
        uses: open-component-model/ocm-action@main
        with:
          action: push_ctf
          comprepo_url: ${{ inputs.componentRepo }}
          force_push: true
          comprepo_password: ${{ secrets.GITHUB_TOKEN }}