name: Golang Test Source
on:
  workflow_call:
    inputs:
      useMake:
        required: false
        type: boolean
        default: false
      coverageThreasholdFile:
        required: false
        type: number
        default: 80
      coverageThreasholdPackage:
        required: false
        type: number
        default: 80
      coverageThreasholdTotal:
        required: false
        type: number
        default: 95
      useLocalCoverageConfig:
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Test Go
        if: ${{ inputs.useMake == false }}
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: Test Make
        if: ${{ inputs.useMake == true }}
        run: make test
      - name: Check Test Coverage
        uses: vladopajic/go-test-coverage@v2
        if: ${{ inputs.useLocalCoverageConfig == false }}
        with:
          profile: cover.out
          # local-prefix: github.com/org/project
          threshold-file: ${{ inputs. coverageThreasholdFile }}
          threshold-package: ${{ inputs. coverageThreasholdPackage }}
          threshold-total: ${{ inputs. coverageThreasholdTotal }}
      - name: Check Test Coverage with Config
        uses: vladopajic/go-test-coverage@v2
        if: ${{ inputs.useLocalCoverageConfig == true }}
        with:
          profile: cover.out
          config: ./.testcoverage.yml
          # local-prefix: github.com/org/project
          threshold-file: ${{ inputs. coverageThreasholdFile }}
          threshold-package: ${{ inputs. coverageThreasholdPackage }}
          threshold-total: ${{ inputs. coverageThreasholdTotal }}