name: Golang Format
on:
  workflow_call:
    inputs:
      useTask:
        required: false
        type: boolean
        default: false
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install Task
        uses: arduino/setup-task@v2
        if: ${{ inputs.useTask }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Format
        if: ${{ !inputs.useTask }}
        run: go fmt ./...
      - name: Format task
        if: ${{ inputs.useTask }}
        run: task fmt