name: Test Helm Chart
on:
  workflow_call:
    inputs:
      branch:
        description: 'branch to checkout'
        required: false
        default: ''
        type: string
      chartRepos:
        required: false
        type: string
        default: ''
      chartsFolder:
        required: false
        type: string
        default: 'charts'
      chartName:
        required: true
        type: string
      additionalTestFilesCommand:
        required: false
        type: string
        default: '-f chart/test-values.yaml'

jobs:
  unittest:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openmfp/gha/infra/helm-unittest:latest@sha256:84209db0e82ae51aea57d497ae1c11343cc641ffbe2ae28a555b0226cb2e959d
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ inputs.branch }}
      - name: Unit Testing Chart
        run: helm unittest "$CHARTS_FOLDER/$CHART_NAME"
        env:
          CHARTS_FOLDER: ${{ inputs.chartsFolder }}
          CHART_NAME: ${{ inputs.chartName }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        with:
          version: v4.2.3
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.x'
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
      - name: Log in to ghcr.io
        run: |
          echo "${GITHUB_TOKEN}" | helm registry login ghcr.io --username "${GITHUB_ACTOR}" --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch "$DEFAULT_BRANCH" --chart-dirs="$CHARTS_FOLDER")
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          CHARTS_FOLDER: ${{ inputs.chartsFolder }}
      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch "$DEFAULT_BRANCH" --chart-dirs="$CHARTS_FOLDER" --validate-maintainers=false --chart-repos="$CHART_REPOS"
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          CHARTS_FOLDER: ${{ inputs.chartsFolder }}
          CHART_REPOS: ${{ inputs.chartRepos }}
  