name: Create Version
on:
  workflow_call:
    inputs:
      prefix:
        description: The Prefix to the created version
        default: ""
        type: string
        required: false
    outputs:
      version:
        description: The prepared Version
        value: ${{ jobs.version.outputs.version }}

jobs:
  # Creates a new semver to be used in the following workflow steps
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Latest Version
        id: get-latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.0
          prefix: ${{ inputs.prefix }}
      - name: Remove prefix from version
        id: remove-prefix
        run: |
          original_string=${{ steps.get-latest-tag.outputs.tag }}
          prefix=${{ inputs.prefix }}
          result=${original_string#"$prefix"}
          echo "::set-output name=cleaned_string::$result"
      - name: Get New Version
        id: bump-semver
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          strict: false
          version: ${{ steps.remove-prefix.outputs.cleaned_string }}
    outputs:
      version: ${{ inputs.prefix }}${{ steps.bump-semver.outputs.minor }}