name: Release
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      chartFolder:
        required: false
        type: string
        default: 'chart'
      release_branch:
        required: false
        type: string
        default: 'main'
      publishCRDChart:
        required: false
        type: boolean
        default: false
      crdChartPath:
        required: false
        type: string
        default: 'charts/crds'
      updateImageTag:
        required: false
        type: boolean
        default: false
      updateVersion:
        required: false
        type: boolean
        default: true
      pushTags:
        required: false
        type: boolean
        default: true
    outputs:
      version:
        description: The chart version that was pushed
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup yq@latest
        if: ${{ inputs.updateVersion }}
        run: |
          if ! command -v yq &>/dev/null
          then
            mkdir -p /home/runner/.local/bin
            wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /home/runner/.local/bin/yq &&\
              chmod +x /home/runner/.local/bin/yq
          fi
      - name: Update Chart version
        if: ${{ inputs.updateVersion }}
        run: |
          yq e -i '.version = "${{ inputs.version }}"' ${{ inputs.chartFolder }}/Chart.yaml
      - name: Update Image Tag
        if: ${{ inputs.updateImageTag && inputs.updateVersion }}
        run: |
          yq e -i '.image.tag = "${{ inputs.version }}"' ${{ inputs.chartFolder }}/values.yaml
      - name: Retrieve helm chart version
        id: chart_version
        run: echo "version=$(yq '.version' ${{ inputs.chartFolder }}/Chart.yaml)" >> $GITHUB_OUTPUT
      - name: Push Helm chart
        uses: bsord/helm-push@v4.2.0
        with:
          useOCIRegistry: true
          username: ${{ github.actor }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url:  oci://ghcr.io/${{ github.repository }}
          chart-folder: ${{ inputs.chartFolder }}
      - name: Update CRD Chart version
        if: ${{ inputs.publishCRDChart && inputs.updateVersion }}
        run: |
          yq e -i '.version = "${{ inputs.version }}"' ${{ inputs.chartFolder }}/${{ inputs.crdChartPath }}/Chart.yaml
      - name: Push CRD Helm chart
        uses: bsord/helm-push@v4.2.0
        if: ${{ inputs.publishCRDChart }}
        with:
          useOCIRegistry: true
          username: ${{ github.actor }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url:  oci://ghcr.io/${{ github.repository }}
          chart-folder: ${{ inputs.chartFolder }}/${{ inputs.crdChartPath }}
      - name: Publish GH Tag
        if: ${{ inputs.pushTags }}
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ inputs.version }}
          message: '${{ inputs.version }}'
    outputs:
      version: ${{ steps.chart_version.outputs.version }}