name: Create Version
on:
  workflow_call:
    inputs:
      prefix:
        description: The Prefix to the created version
        default: ""
        type: string
        required: false
      use_semver_action:
        description: Use the semver action to create the version
        default: false
        type: boolean
        required: false
    outputs:
      version:
        description: The prepared Version
        value: ${{ jobs.version.outputs.version }}

jobs:
  # Creates a new semver to be used in the following workflow steps
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        if: ${{ inputs.use_semver_action }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          majorList: BREAKING CHANGE, BREAKING, MAJOR
          minorList: FEATURE, Feature, feature, FEAT, Feat, feat
          patchList: FIX, Fix, fix, FIXED, Fixed, fixed, chore, config, conf, cofiguration, configure, build, chore, ci, rebuild, doc, docu, document, documentation, dependencies

      - name: Get Latest Version
        id: get-latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.0
          prefix: ${{ inputs.prefix || '[0-9]' }}
      - name: Remove prefix from version
        id: remove-prefix
        run: |
          original_string=${{ steps.get-latest-tag.outputs.tag }}
          prefix=${{ inputs.prefix }}
          result=${original_string#"$prefix"}
          echo "cleaned_string=$result" >> $GITHUB_ENV
      - name: Get New Version
        id: bump-semver
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          strict: false
          version: ${{ env.cleaned_string }}
    outputs:
      version: ${{ inputs.use_semver_action && steps.semver.next || format('{0}{1}', inputs.prefix, steps.bump-semver.outputs.minor) }}