name: Update-Version-File

on:
  workflow_call:
    inputs:
      componentVersionKey:
        required: true
        type: string
      githubUser:
        required: false
        default: "openmfp-technical-user"
        type: string
      githubUserEmail:
        required: false
        default: "openmfp@gmail.com"
        type: string
      versionsFile:
        required: false
        default: "versions.yaml"
        type: string
      versionRepo:
        required: false
        default: "openmfp/versions"
        type: string
      versionRepoBranch:
        required: false
        default: "dev"
        type: string
      version:
        required: true
        type: string

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          app-id: "838464"
          private-key: ${{ secrets.OPENMFP_PUBLISHER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            versions
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ inputs.versionRepo }}
          ref: ${{ inputs.versionRepoBranch }}
      - name: Setup yq@latest
        run: |
          if ! command -v yq &>/dev/null
          then
            mkdir -p /home/runner/.local/bin
            wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /home/runner/.local/bin/yq &&\
              chmod +x /home/runner/.local/bin/yq
          fi
      - name: Update till successful
        shell: bash
        env:
          GITHUB_USER: ${{ inputs.githubUser }}
          GITHUB_USER_EMAIL: ${{ inputs.githubUserEmail }}
          VERSION_REPO_BRANCH: ${{ inputs.versionRepoBranch }}
          COMPONENT_VERSION_KEY: ${{ inputs.componentVersionKey }}
          VERSION: ${{ inputs.version }}
          VERSIONS_FILE: ${{ inputs.versionsFile }}
        run: |
          count=1

          git config --global user.name "$GITHUB_USER"
          git config --global user.email "$GITHUB_USER_EMAIL"

          clean_and_retry () {
            echo "trying for the $count time, to push"
            count=$((count+1))
            if [ $count -gt 10 ]
            then
              printf 'too many attempts, I give up' >&2
              exit 1
            fi
            git reset --hard HEAD^1
            git fetch
            git rebase "origin/$VERSION_REPO_BRANCH"
            apply_change_and_commit
            git push origin "$VERSION_REPO_BRANCH" || clean_and_retry
          }

          apply_change_and_commit () {
            yq e -i '.[strenv(COMPONENT_VERSION_KEY)] = strenv(VERSION)' "$VERSIONS_FILE"
            echo "set version $VERSION for $COMPONENT_VERSION_KEY in $VERSIONS_FILE"
            git add "$VERSIONS_FILE"
            git commit -m "Updating version of [$COMPONENT_VERSION_KEY] to $VERSION" || echo "version was already up to date"
          }

          apply_change_and_commit
          git push origin "$VERSION_REPO_BRANCH" || clean_and_retry