name: Node Test
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
      workingDirectory:
        required: false
        type: string
        default: './'
      workingDirectoryDist:
        required: false
        type: string
        default: './dist'
      publishFromDist:
        required: false
        type: boolean
        default: false
      release_branch:
        description: 'Name of the release branch'
        required: false
        type: string
        default: 'main'
      node_version:
        description: 'Node version to use'
        required: false
        type: string
        default: '20'

env:
  BRANCH: ${{ github.head_ref || github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    if: env.BRANCH == format('refs/heads/{0}',inputs.release_branch)
    steps:
    - name: Setup Git
      run: |
        git config --global user.name 'OpenMFP Technical User'
        git config --global user.email 'openmfp@gmail.com'
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: "838464"
        private-key: ${{ secrets.OPENMFP_PUBLISHER_PRIVATE_KEY }}
    - uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://npm.pkg.github.com/
    - uses: actions/download-artifact@v4
      with:
        name: target
        path: dist
      continue-on-error: true
    - name: Get npm version
      id: get-npm-version
      run: |
        NPM_VERSION=$(cat package.json | jq '.version' -r)
        echo "NPM version: $NPM_VERSION"
        echo "npm_version=$NPM_VERSION" >> $GITHUB_ENV
      working-directory: ${{ inputs.workingDirectory }}
    - name: Get New Version
      id: bump-semver
      uses: WyriHaximus/github-action-next-semvers@v1
      with:
        strict: false
        version: ${{ env.npm_version }}
    - name: Publish from dist folder
      if: ${{ inputs.publishFromDist }}
      run: |
        npm version ${{ steps.bump-semver.outputs.minor }}
        npm publish
        cd ..
        npm version ${{ steps.bump-semver.outputs.minor }} -m "[no ci] Release ${{ steps.bump-semver.outputs.minor }}"
      working-directory:
        ${{ inputs.workingDirectoryDist }}
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Publish
      if: ${{ !inputs.publishFromDist }}
      run: |
        npm version ${{ steps.bump-semver.outputs.minor }} -m "[no ci] Release ${{ steps.bump-semver.outputs.minor }}"
        npm publish
      working-directory:
        ${{ inputs.workingDirectory }}
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    # npm version does not commit on subdirectories, so we commit manually
    - name: Commit and Tag
      if: inputs.workingDirectory != './'
      run: |
        git add .
        git commit -m "[no ci] Release ${{ steps.bump-semver.outputs.minor }}"
        git fetch
        git rebase
        git tag -a ${{ steps.bump-semver.outputs.minor }} -m "[no ci] Release ${{ steps.bump-semver.outputs.minor }}"
    - name: Push
      run: |
        git push origin
        git push origin --tags
      working-directory: ${{ inputs.workingDirectory }}
