name: Release
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      version:
        required: true
        type: string
      chartFolder:
        required: false
        type: string
        default: 'chart'
      release_branch:
        required: false
        type: string
        default: 'main'
      skip_image_tag:
        required: false
        type: boolean
        default: false
      publishCRDChart:
        required: false
        type: boolean
        default: false
      crdChartPath:
        required: false
        type: string
        default: 'charts/crds'

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup yq@latest
        run: |
          if ! command -v yq &>/dev/null
          then
            mkdir -p /home/runner/.local/bin
            wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /home/runner/.local/bin/yq &&\
              chmod +x /home/runner/.local/bin/yq
          fi
      - name: Update Chart version
        run: |
          yq e -i '.version = "${{ inputs.version }}"' ${{ inputs.chartFolder }}/Chart.yaml
      - name: Update Image Tag
        if: ${{ !inputs.skip_image_tag }}
        run: |
          yq e -i '.image.tag = "${{ inputs.version }}"' ${{ inputs.chartFolder }}/values.yaml
      - name: Push Helm chart
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          username: ${{ github.actor }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url:  oci://ghcr.io/${{ inputs.imageTagName }}/helm
          chart-folder: ${{ inputs.chartFolder }}
      - name: Update CRD Chart version
        if: ${{ inputs.publishCRDChart }}
        run: |
          yq e -i '.version = "${{ inputs.version }}"' ${{ inputs.chartFolder }}/${{ inputs.crdChartPath }}/Chart.yaml
      - name: Push CRD Helm chart
        uses: bsord/helm-push@v4.1.0
        if: ${{ inputs.publishCRDChart }}
        with:
          useOCIRegistry: true
          username: ${{ github.actor }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url:  oci://ghcr.io/${{ inputs.imageTagName }}/helm/crds
          chart-folder: ${{ inputs.chartFolder }}/${{ inputs.crdChartPath }}
      - name: Publish GH Tag
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ inputs.version }}
          message: '${{ inputs.version }}'
