name: Docker Build and Push
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      version:
        required: true
        type: string
      release_branch:
        required: false
        type: string
        default: 'main'
jobs:
  dockerARM:
    runs-on: macos-13
    steps:
      - uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Setup Docker
        run: |
          brew install docker-buildx
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          echo ${{secrets.GITHUB_TOKEN}} | docker buildx build \
            --secret id=github_token,src=/dev/stdin \
            --tag ${{inputs.imageTagName}}:${{inputs.version}} .
      - name: Push Docker image
        if: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
        run: docker push ${{inputs.imageTagName}}:${{inputs.version}}