name: Docker Build and Push
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      version:
        required: true
        type: string
      release_branch:
        required: false
        type: string
        default: 'main'
jobs:
  dockerARM:
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        run: |
          brew install docker colima docker-buildx
      - name: Start Docker container runtimes
        run: |
          colima start
      - name: Test for docker
        run: docker --version
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: echo ${{secrets.GITHUB_TOKEN}} | docker buildx build --secret id=NODE_AUTH_TOKEN,src=/dev/stdin --tag=${{inputs.imageTagName}}:${{inputs.version}} .
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        with:
#          push: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
#          platforms: ${{ inputs.arch }}
#          tags: ${{ inputs.imageTagName }}:${{ inputs.version }}
#          secrets: |
#            NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}