name: Golang Test Source
on:
  workflow_call:
    inputs:
      useMake:
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Format
        run: go fmt ./...
      - name: Vet
        run: go vet ./...
      - name: Test Go
        if: ${{ inputs.useMake == false }}
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: Test Make
        if: ${{ inputs.useMake == true }}
        run: make test
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          # local-prefix: github.com/org/project
          threshold-file: 80
          threshold-package: 80
          threshold-total: 95