name: Test Helm Chart
on:
  workflow_call:
    inputs:
      branch:
        description: 'branch to checkout'
        required: false
        default: ''
        type: string
      chartRepos:
        required: false
        type: string
        default: ''
      chartsFolder:
        required: false
        type: string
        default: 'charts'
      chartName:
        required: true
        type: string
      additionalTestFilesCommand:
        required: false
        type: string
        default: '-f chart/test-values.yaml'

jobs:
  unittest:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openmfp/gha/infra/helm-unittest:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Unit Testing Chart
        run: helm unittest ${{ inputs.chartsFolder }}/${{ inputs.chartName }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs=${{ inputs.chartsFolder }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --chart-dirs=${{ inputs.chartsFolder }} --validate-maintainers=false --chart-repos=${{ inputs.chartRepos }}
  
