name: Scan kubernetes vulnerability
on:
  workflow_call:
    inputs:
      chartsFolder:
        required: false
        type: string
        default: 'charts'

jobs:
  vulnerability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
