name: Create Version
on:
  workflow_call:
    outputs:
      version:
        description: The prepared Version
        value: ${{ jobs.version.outputs.version }}

jobs:
  # Creates a new semver to be used in the following workflow steps
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}
      
      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          majorList: BREAKING CHANGE, BREAKING, MAJOR
          minorList: FEATURE, Feature, feature, FEAT, Feat, feat
          patchList: FIX, Fix, fix, FIXED, Fixed, fixed, chore, config, conf, cofiguration, configure, build, chore, ci, rebuild, doc, docu, document, documentation, dependencies
          prefix: v
          noNewCommitBehavior: warn

    outputs:
      version: ${{ steps.semver.outputs.next }}
