name: Create GitHub Release

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      version:
        description: 'The version to release (e.g. 1.2.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Create GitHub Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          generateReleaseNotes: true
          tag: ${{ inputs.version }}
          name: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
