name: Docker Build and Push
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      version:
        required: true
        type: string
      release_branch:
        required: false
        type: string
        default: 'main'
      multiarch:
        required: false
        type: boolean
        default: true

jobs:
  docker:
    runs-on: ubuntu-latest-large
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          push: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
          platforms: ${{ (inputs.multiarch && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          tags: ${{ inputs.imageTagName }}:${{ inputs.version }}
          secrets: |
            NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Publish GH Tag
        if: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ inputs.version }}
          message: '${{ inputs.version }}'
