name: Node Test
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Setup Git
      run: |
        git config --global user.name 'OpenMFP Technical User'
        git config --global user.email 'openmfp@gmail.com'
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: "838464"
        private-key: ${{ secrets.OPENMFP_PUBLISHER_PRIVATE_KEY }}
    - uses: actions/checkout@v2
      with:
        token: ${{ steps.app-token.outputs.token }}
    - uses: actions/setup-node@v1
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/
    - name: Change Version
      uses: reedyuk/npm-version@1.1.1
      with:
        version: ${{inputs.version}}
        git-tag-version: 'true'
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Commit, Tag and Push
      run: |
        git push origin
        git push origin --tags