name: Docker Build and Push
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      version:
        required: true
        type: string
      release_branch:
        required: false
        type: string
        default: 'main'
      arch:
        required: false
        type: string
        default: true
jobs:
  docker:
    runs-on: ${{ inputs.arch == 'linux/arm64' && 'macos-latest-large' || 'ubuntu-latest' }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test for docker
        run: docker --version
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        with:
#          push: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
#          platforms: ${{ inputs.arch }}
#          tags: ${{ inputs.imageTagName }}:${{ inputs.version }}
#          secrets: |
#            NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
