name: Create Version
on:
  workflow_call:
    outputs:
      version:
        description: The prepared Version
        value: ${{ jobs.version.outputs.version }}

jobs:
  # Creates a new semver to be used in the following workflow steps
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Latest Version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
          initial_version: 0.0.0
          with_initial_version: true
      - name: Get New Version
        uses: thejeff77/action-bump-semver@v1.0.0
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor
    outputs:
      version: ${{ steps.bump-semver.outputs.new_version }}