name: Publish Version

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to be pushed to the GitHub repository'
        required: true
        type: string

jobs:
  publishVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Publish GitHub Tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ inputs.version }}
          message: '${{ inputs.version }}'