name: pipeline
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      chartFolder:
        required: false
        type: string
        default: 'chart'
      componentVersionKey:
        required: true
        type: string
      additionalTestFilesCommand:
        required: false
        type: string
        default: '-f chart/test-values.yaml'
jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml

  test:
    uses: ./.github/workflows/job-node-test.yml

  testChart:
    uses: ./.github/workflows/job-test-chart.yml
    with:
      chartFolder: ${{ inputs.chartFolder }}
      additionalTestFilesCommand: ${{ inputs.additionalTestFilesCommand }}
    secrets: inherit

  dockerBuildAndPush:
    needs: [createVersion]
    uses: ./.github/workflows/job-docker-build-push.yml
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ needs.createVersion.outputs.version }}
    secrets: inherit

  release:
    needs: [createVersion,dockerBuildAndPush, test,testChart]
    uses: ./.github/workflows/job-release.yml
    secrets: inherit
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ needs.createVersion.outputs.version }}
      chartFolder: ${{ inputs.chartFolder }}

  updateVersionFile:
    needs: [createVersion, release]
    uses: ./.github/workflows/job-update-version-file.yml
    secrets: inherit
    with:
      componentVersionKey: ${{ inputs.componentVersionKey }}
      version: ${{ needs.createVersion.outputs.version }}