name: pipeline
on:
  push:

jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml

  build:
    uses: ./.github/workflows/job-node-test.yml

  publish:
    needs: [createVersion, build]
    uses: ./.github/workflows/job-node-publish.yml
    secrets: inherit
    with:
      version: ${{ needs.createVersion.outputs.version }}

