name: pipeline
on:
  workflow_call:
    inputs:
      useMake:
        required: false
        type: boolean
        default: false
      coverageThreasholdFile:
        required: false
        type: number
        default: 80
      coverageThreasholdPackage:
        required: false
        type: number
        default: 80
      coverageThreasholdTotal:
        required: false
        type: number
        default: 95
      useLocalCoverageConfig:
        required: false
        type: boolean
        default: false
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.createVersion.outputs.version }}

jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml
    secrets: inherit
  
  lint:
    uses: ./.github/workflows/job-golang-lint.yml

  testSource:
    uses: ./.github/workflows/job-golang-test-source.yml
    with:
      useMake: ${{ inputs.useMake }}
      useLocalCoverageConfig: ${{ inputs.useLocalCoverageConfig }}
      coverageThreasholdFile: ${{ inputs.coverageThreasholdFile }}
      coverageThreasholdPackage: ${{ inputs.coverageThreasholdPackage }}
      coverageThreasholdTotal: ${{ inputs.coverageThreasholdTotal }}
  format:
    uses: ./.github/workflows/job-golang-format.yml

  publishVersion:
    if: github.ref == 'refs/heads/main'
    needs: [createVersion,lint,testSource,format]
    uses: ./.github/workflows/job-version-publish.yaml
    with:
      version: ${{ needs.createVersion.outputs.version }}
    secrets: inherit