name: pipeline-chart
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      chartFolder:
        required: false
        type: string
        default: 'chart'
      chartName:
        required: true
        type: string
      additionalTestFilesCommand:
        required: false
        type: string
        default: '-f chart/test-values.yaml'
      release_branch:
        required: false
        type: string
        default: 'main'
      pushTags:
        required: false
        type: boolean
        default: false
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.createVersion.outputs.version }}

jobs:
  createVersion:
    if: ${{ inputs.pushTags }}
    uses: ./.github/workflows/job-create-version.yml
    secrets: inherit
  
  testChart:
    uses: ./.github/workflows/job-test-chart.yml
    with:
      chartsFolder: ${{ inputs.chartFolder }}
      chartName: ${{ inputs.chartName }}
      additionalTestFilesCommand: ${{ inputs.additionalTestFilesCommand }}
    secrets: inherit

  release:
    needs: [testChart]
    uses: ./.github/workflows/job-release-chart.yml
    secrets: inherit
    with:
      updateVersion: false
      pushTags: ${{ inputs.pushTags }}
      update_image_tag: false
      chartFolder: ${{ inputs.chartFolder }}/${{ inputs.chartName }}
      release_branch: ${{ inputs.release_branch }}
      imageTagName: ${{ inputs.imageTagName }}
