name: pipeline
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      chartFolder:
        required: false
        type: string
        default: 'chart'
jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml

  test:
    uses: ./.github/workflows/job-node-test.yml

  dockerBuildAndPush:
    needs: [createVersion]
    uses: ./.github/workflows/job-docker-build-push.yml
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ needs.createVersion.outputs.version }}
    secrets: inherit

  release:
    needs: [createVersion,dockerBuildAndPush, test]
    uses: ./.github/workflows/job-release.yml
    secrets: inherit
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ needs.createVersion.outputs.version }}
      chartFolder: ${{ inputs.chartFolder }}