name: pipeline
on:
  workflow_call:
    inputs:
      workingDirectory:
        required: false
        type: string
        default: './'
      publishFromDist:
        required: false
        type: boolean
        default: false
      release_branch:
        description: 'Name of the release branch'
        required: false
        type: string
        default: 'main'
      node_version:
        description: 'Node version to use'
        required: false
        type: string
        default: '20'

jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml

  build:
    uses: ./.github/workflows/job-node-test.yml
    secrets: inherit
    with:
      workingDirectory: ${{ inputs.workingDirectory }}
      release_branch: ${{ inputs.release_branch }}

  publish:
    needs: [createVersion, build]
    uses: ./.github/workflows/job-node-publish.yml
    secrets: inherit
    with:
      version: ${{ needs.createVersion.outputs.strictVersion }}
      workingDirectory: ${{ inputs.workingDirectory }}
      publishFromDist: ${{ inputs.publishFromDist }}
      release_branch: ${{ inputs.release_branch }}
      node_version: ${{ inputs.node_version }}

