name: pipeline
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      componentVersionKey:
        required: true
        type: string
      release_branch:
        description: 'Name of the release branch'
        required: false
        type: string
        default: 'main'
      node_version:
        description: 'Node version to use'
        required: false
        type: string
        default: '20'
jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml

  test:
    uses: ./.github/workflows/job-node-test.yml
    with:
      release_branch: ${{ inputs.release_branch }}
      node_version: ${{ inputs.node_version }}

  dockerBuildAndPushAMD:
    needs: [createVersion]
    uses: ./.github/workflows/job-docker-build-push-arch.yml
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ needs.createVersion.outputs.version }}
      release_branch: ${{ inputs.release_branch }}
      arch: 'linux/amd64'
    secrets: inherit

  dockerBuildAndPushARM:
    needs: [createVersion]
    uses: ./.github/workflows/job-docker-build-push-arch.yml
    if: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ needs.createVersion.outputs.version }}
      release_branch: ${{ inputs.release_branch }}
      arch: 'linux/arm64'
    secrets: inherit

  pushGithubTag:
    needs: [test, dockerBuildAndPushAMD,dockerBuildAndPushARM,createVersion]
    if: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
    uses: ./.github/workflows/job-push-tag.yml
    with:
      version: ${{ needs.createVersion.outputs.version }}
    secrets: inherit

  updateVersion:
    needs: [createVersion,pushGithubTag]
    if: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
    uses: ./.github/workflows/job-chart-version-update.yml
    secrets: inherit
    with:
      appVersion: ${{ needs.createVersion.outputs.version }}
      chart: ${{ github.event.repository.name }}