name: pipeline
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      chartFolder:
        required: false
        type: string
        default: 'chart'
      additionalTestFilesCommand:
        required: false
        type: string
        default: '-f chart/test-values.yaml'
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.createVersion.outputs.version }}

jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml
    secrets: inherit
  
  validateChart:
    uses: ./.github/workflows/job-chart-validate.yml
    with:
      chartFolder: ${{ inputs.chartFolder }}
      additionalTestFilesCommand: ${{ inputs.additionalTestFilesCommand }}
    secrets: inherit

  lint:
    uses: ./.github/workflows/job-golang-lint.yml

  dockerBuildAndPush:
    needs: [createVersion]
    uses: ./.github/workflows/job-docker-build-push.yml
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ needs.createVersion.outputs.version }}
    secrets: inherit

  release:
    needs: [dockerBuildAndPush,validateChart,createVersion,lint]
    uses: ./.github/workflows/job-release.yml
    secrets: inherit
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ needs.createVersion.outputs.version }}
      chartFolder: ${{ inputs.chartFolder }}