name: pipeline
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      useTask:
        required: false
        type: boolean
        default: false
      coverageThresholdFile:
        required: false
        type: number
        default: 80
      coverageThresholdPackage:
        required: false
        type: number
        default: 80
      coverageThresholdTotal:
        required: false
        type: number
        default: 95
      useLocalCoverageConfig:
        required: false
        type: boolean
        default: false
      release_branch:
        required: false
        type: string
        default: 'main'
      repoVersionUpdate:
        required: false
        type: string
        default: 'openmfp/helm-charts-priv'
      doubleTagging:
        required: false
        type: boolean
        default: false
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'
      apiPackagePath:
        required: false
        type: string
        default: ''
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.createVersion.outputs.version }}
  workflow_dispatch:
    inputs:
      imageTagName:
        required: true
        type: string
      useTask:
        required: false
        type: boolean
        default: false
      coverageThresholdFile:
        required: false
        type: number
        default: 80
      coverageThresholdPackage:
        required: false
        type: number
        default: 80
      coverageThresholdTotal:
        required: false
        type: number
        default: 95
      useLocalCoverageConfig:
        required: false
        type: boolean
        default: false
      release_branch:
        required: false
        type: string
        default: 'main'
      repoVersionUpdate:
        required: false
        type: string
        default: 'openmfp/helm-charts-priv'
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'


jobs:
  auto-labeler:
    if: ${{ (github.head_ref || github.ref) != format('refs/heads/{0}',inputs.release_branch) }}
    uses: ./.github/workflows/job-auto-labeler.yml
    secrets: inherit

  createVersion:
    if: ${{ (github.head_ref || github.ref) == format('refs/heads/{0}',inputs.release_branch) }}
    uses: ./.github/workflows/job-create-version.yml
    secrets: inherit
    with:
      apiPackagePath: ${{ inputs.apiPackagePath }}
  
  lint:
    uses: ./.github/workflows/job-golang-lint.yml
    with:
      useTask: ${{ inputs.useTask }}
