name: pipeline
on:
  workflow_call:
    inputs:
      useMake:
        required: false
        type: boolean
        default: false
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.createVersion.outputs.version }}

jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml
    secrets: inherit
  
  lint:
    uses: ./.github/workflows/job-golang-lint.yml

  testSource:
    uses: ./.github/workflows/job-golang-test-source.yml
    with:
      useMake: ${{ inputs.useMake }}

  publishVersion:
    needs: [createVersion,lint,testSource]
    uses: ./.github/workflows/job-version-publish.yaml
    with:
      version: v${{ needs.createVersion.outputs.version }}
    secrets: inherit