name: pipeline
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      useTask:
        required: false
        type: boolean
        default: false
      coverageThreasholdFile:
        required: false
        type: number
        default: 80
      coverageThreasholdPackage:
        required: false
        type: number
        default: 80
      coverageThreasholdTotal:
        required: false
        type: number
        default: 95
      useLocalCoverageConfig:
        required: false
        type: boolean
        default: false
      release_branch:
        required: false
        type: string
        default: 'main'
      repoVersionUpdate:
        required: false
        type: string
        default: 'openmfp/helm-charts-priv'
      doubleTagging:
        required: false
        type: boolean
        default: false
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.createVersion.outputs.version }}
  workflow_dispatch:
    inputs:
      imageTagName:
        required: true
        type: string
      useTask:
        required: false
        type: boolean
        default: false
      coverageThreasholdFile:
        required: false
        type: number
        default: 80
      coverageThreasholdPackage:
        required: false
        type: number
        default: 80
      coverageThreasholdTotal:
        required: false
        type: number
        default: 95
      useLocalCoverageConfig:
        required: false
        type: boolean
        default: false
      release_branch:
        required: false
        type: string
        default: 'main'
      repoVersionUpdate:
        required: false
        type: string
        default: 'openmfp/helm-charts-priv'

jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml
    secrets: inherit
  
  lint:
    uses: ./.github/workflows/job-golang-lint.yml
    with:
      useTask: ${{ inputs.useTask }}

  testSource:
    uses: ./.github/workflows/job-golang-test-source.yml
    with:
      useTask: ${{ inputs.useTask }}
      useLocalCoverageConfig: ${{ inputs.useLocalCoverageConfig }}
      coverageThreasholdFile: ${{ inputs.coverageThreasholdFile }}
      coverageThreasholdPackage: ${{ inputs.coverageThreasholdPackage }}
      coverageThreasholdTotal: ${{ inputs.coverageThreasholdTotal }}

  dockerBuildAndPush:
    needs: [createVersion,lint,testSource]
    uses: ./.github/workflows/job-docker-build-push.yml
    with:
      imageTagName: ${{ inputs.imageTagName }}
      version: ${{ needs.createVersion.outputs.version }}
      release_branch: ${{ inputs.release_branch }}
      multiarch: true
    secrets: inherit

  updateVersion:
    needs: [createVersion, dockerBuildAndPush]
    if: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) }}
    uses: ./.github/workflows/job-chart-version-update.yml
    secrets: inherit
    with:
      appVersion: ${{ needs.createVersion.outputs.version }}
      chart: ${{ github.event.repository.name }}
      targetRepository: ${{ inputs.repoVersionUpdate }}

  pushPrefixedGHTag:
    runs-on: ubuntu-latest
    needs: [createVersion]
    steps:
      - name: Create second tag
        id: create-second-tag
        if: ${{ inputs.doubleTagging == true }}
        run: |
          echo "Creating second tag"
          result = ${{ needs.createVersion.outputs.version }}
          if [[ $result == v* ]]; then
            result=${result:1}
          else
            result="v$result"
          fi
          echo "::set-output name=secondtag_string::$result"
      - name: Publish Prefixed GH Tag
        id: push-prefixed-gh-tag
        if: ${{ inputs.doubleTagging == true }}
        # if: ${{ github.ref == format('refs/heads/{0}',inputs.release_branch) && inputs.doubleTagging == true }}
        # uses: thejeff77/action-push-tag@v1.0.0
        # with:
        #   tag: v${{ inputs.version }}
        #   message: 'v${{ inputs.version }}'
        run: |
          echo v${{ needs.create-second-tag.outputs.secondtag_string }}