name: pipeline-chart
on:
  workflow_call:
    inputs:
      imageTagName:
        required: true
        type: string
      chartFolder:
        required: false
        type: string
        default: 'chart'
      additionalTestFilesCommand:
        required: false
        type: string
        default: '-f chart/test-values.yaml'
      release_branch:
        required: false
        type: string
        default: 'main'
    outputs:
      version:
        description: "The created Version"
        value: ${{ jobs.createVersion.outputs.version }}

jobs:
  testChart:
    uses: ./.github/workflows/job-test-chart.yml
    with:
      chartFolder: ${{ inputs.chartFolder }}
      additionalTestFilesCommand: ${{ inputs.additionalTestFilesCommand }}
    secrets: inherit

  testChartVersion:
    uses: ./.github/workflows/job-test-chart-version.yml
    with:
      chartFolder: ${{ inputs.chartFolder }}
    secrets: inherit

  release:
    needs: [testChart,testChartVersion]
    uses: ./.github/workflows/job-release-chart.yml
    secrets: inherit
    with:
      updateVersion: false
      pushTags: false
      skip_image_tag: true
      chartFolder: ${{ inputs.chartFolder }}
      release_branch: ${{ inputs.release_branch }}
      imageTagName: ${{ inputs.imageTagName }}