name: pipeline
on:
  workflow_call:
    inputs:
      workingDirectory:
        required: false
        type: string
        default: './'

jobs:
  createVersion:
    uses: ./.github/workflows/job-create-version.yml

  build:
    uses: ./.github/workflows/job-node-test.yml
    secrets: inherit
    with:
      workingDirectory: ${{ inputs.workingDirectory }}

  publish:
    needs: [createVersion, build]
    uses: ./.github/workflows/job-node-publish.yml
    secrets: inherit
    with:
      version: ${{ needs.createVersion.outputs.version }}
      workingDirectory: ${{ inputs.workingDirectory }}

